### ISSUE TITLE
Trouble installing extension

### ISSUE THREAD

**Issue by wokremse** [christianbors/OpenRefineQualityMetrics#1]
I have downloaded and installed Open Refine 3.1 and got it to run locally. Then I did the following:

1. git clone this repo into \openrefine-3.1\webapp\extensions
2. Call bower install in openrefine-3.1\webapp\extensions\OpenRefineQualityMetrics
3. Restart Open Refine by calling \openrefine-3.1\openrefine.exe

I then run into the 500 error below. I am running Windows 10. I am not sure what I got wrong, any help would be appreachiated.

`   Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module metric-doc [edu.mit.simile.butterfly.ButterflyModuleImpl]
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
	at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
	at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at com.google.refine.RefineServer.configure(Refine.java:291)
	at com.google.refine.RefineServer.init(Refine.java:203)
	at com.google.refine.Refine.init(Refine.java:109)
	at com.google.refine.Refine.main(Refine.java:103)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/C:/Users/wkremser/Desktop/openrefine-3.1/webapp/extensions/OpenRefineQualityMetrics/module/MOD-INF/controller.js#38)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:998)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1053)
	at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:1016)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen.file__C__Users_wkremser_Desktop_openrefine_3_1_webapp_extensions_OpenRefineQualityMetrics_module_MOD_INF_controller_js_6._c_init_1(file:/C:/Users/wkremser/Desktop/openrefine-3.1/webapp/extensions/OpenRefineQualityMetrics/module/MOD-INF/controller.js:38)
	at org.mozilla.javascript.gen.file__C__Users_wkremser_Desktop_openrefine_3_1_webapp_extensions_OpenRefineQualityMetrics_module_MOD_INF_controller_js_6.call(file:/C:/Users/wkremser/Desktop/openrefine-3.1/webapp/extensions/OpenRefineQualityMetrics/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.file__C__Users_wkremser_Desktop_openrefine_3_1_webapp_extensions_OpenRefineQualityMetrics_module_MOD_INF_controller_js_6.call(file:/C:/Users/wkremser/Desktop/openrefine-3.1/webapp/extensions/OpenRefineQualityMetrics/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
	at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
	... 8 more`

**Comment by christianbors** [comment]
Hello,

The Extension is currently outdated and will not run on the newest OpenRefine version any more, since the project transitioned to a different build structure. That broke support for my extension.
I will work on fixing the project build structure in the near future.
The only way possible for is checking out an old revision of OpenRefine's git project and running the extension with this old revision.
Sorry for the inconvenience.

**Comment by JanC** [comment]
Hey @christianbors,
what was the latest OpenRefine version where this extension used to work?
cheers
